### PR TITLE
Fix order of contents #72

### LINKED ISSUE #72: Fix order of contents
**Overview (Required)**
- The current content order is the oldest, but it should be the newest.

**Steps To Reproduce**

1. Go to 'Home'

**Expected behavior**
A new article is displayed at the top.

**Screenshots**
image

**Additional context**
https://github.com/DroidKaigi/conference-app-2021/blob/f6d311de4fb522d412f5786022474305b7048ac0/data/repository/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/FeedRepositoryImpl.kt#L21

### PR DESCRIPTION
**Pull request by kumamotone**
## Issue
- close #72

## Overview (Required)

Fix order of contents #72.
I simply used `reversed()`.

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by kumamotone** [comment]
```
      data/repository/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/FeedRepositoryImpl.kt
          @@ -18,9 +18,11 @@
           ····················emit(feedApi.fetch())
           ················}
           ············)·{·favorites,·apiFeed·->
          -················FeedContents(apiFeed
          -····················.sortedBy·{·it.publishedAt·}
```

aww ok

**Comment by tomoya0x00** [comment]
👀

File: data/repository/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/FeedRepositoryImpl.kt [hunk 1]
```diff
@@ -18,7 +18,7 @@ open class FeedRepositoryImpl(
                     emit(feedApi.fetch())
                 }
             ) { favorites, apiFeed ->
-                FeedContents(apiFeed.sortedBy { it.publishedAt }, favorites)
+                FeedContents(apiFeed.sortedBy { it.publishedAt }.reversed(), favorites)
```
Comment (tomoya0x00) [inline data/repository/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/FeedRepositoryImpl.kt:21]: It looks work fine! But do you think about using sortedByDescending() instead of sortedBy() and reversed() ?

**Review by tomoya0x00 — COMMENTED** [review]
@kumamotone Thanks for your PR! Could you check my comment?

File: data/repository/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/FeedRepositoryImpl.kt (hunk 1 above)
Comment (kumamotone) [reply data/repository/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/FeedRepositoryImpl.kt]: That sounds better >< Thank you!

**Review by takahirom — APPROVED** [review]
LGTM 👍
