### PR TITLE
fix dependencies arbor

### LINKED ISSUE #228: Can we use common artifact for Arbor?
## Kind (Required)

- Improvement

 ## Overview (Required)

- We use JVM artifact. But Probably In recent Kotlin MPPs, you can only refer to common artifact.
- Like `const val abor = "com.ToxicBakery.logging:arbor:1.35.72"`
- 
- Please delete "com.ToxicBakery.logging:arbor-android" and "com.ToxicBakery.logging:arbor-jvm" dependency and use "com.ToxicBakery.logging:arbor" 🙏 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/pull/221/files#diff-0f9d3ee70139178b0d6cca6bf4a909174a00934c74f3dc32c6afca2ed335d647R104

### PR DESCRIPTION
**Pull request by akihiro-n**
## Issue
- close #228 

## Overview (Required)
- Fixed dependencies
  - delete ```com.ToxicBakery.logging:arbor-android``` and ```com.ToxicBakery.logging:arbor-jvm``` dependency
  - use ```com.ToxicBakery.logging:common```
- Fixed import that cannot be referenced due to changes
  - delete ```import com.toxicbakery.logging.LogCatSeedling``` (Cannot be referenced)
  - add ```import com.toxicbakery.logging.Seedling```

### CODE REVIEW

**Review by takahirom — APPROVED** [review]
Thank you! LGTM 👍

File: android/src/main/java/io/github/droidkaigi/feeder/ArborInitializer.kt [hunk 1]
```diff
@@ -3,11 +3,11 @@ package io.github.droidkaigi.feeder
 import android.content.Context
 import androidx.startup.Initializer
 import com.toxicbakery.logging.Arbor
-import com.toxicbakery.logging.LogCatSeedling
+import com.toxicbakery.logging.Seedling
 
 class ArborInitializer : Initializer<Unit> {
     override fun create(context: Context) {
-        Arbor.sow(LogCatSeedling())
+        Arbor.sow(Seedling())
```
Comment (takahirom) [inline android/src/main/java/io/github/droidkaigi/feeder/ArborInitializer.kt:10]: Thank you! Perhaps only the android module should have depended on android abor.
I will try to make another issue. 👍

**Review by takahirom — APPROVED** [review]
