### PR TITLE
Fix to remove border of feed item image

### LINKED ISSUE #240: Remove border of feed image
**Overview (Required)**
- The feed image has a border that is not in the design instructions and needs to be removed.

**Steps To Reproduce**

1. Launch App
2. Show home screen

**Expected behavior**
It is expected that there will be no border in the feed image.

**Screenshots**

Figma design | App 
:--: | :--:
スクリーンショット 2021-03-02 21 12 36 | figma

**Env:**
 - Device: Pixel
 - OS: Android 8.0
 - master 9fe747b

**Additional context**
It has been discussed in the Issue below.
https://github.com/DroidKaigi/conference-app-2021/issues/88#issuecomment-788880361

### PR DESCRIPTION
**Pull request by maho-ya**
## Issue
- close #240

## Overview (Required)
- Bug Fix. Remove border of feed item image that are not in the Figma design.

## Links
- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=1%3A305

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Review by takahirom — APPROVED** [review]
LGTM!🙏

File: uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt [hunk 1]
```diff
@@ -82,7 +81,7 @@ fun FeedItem(
                 }
                 .width(96.dp)
 //                .aspectRatio(16F / 9F)
-                .aspectRatio(1F / 1F).border(1.dp, Color.Black),
+                .aspectRatio(1F / 1F),
```
Comment (mightyfrog) [inline uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt:84]: .clip(shape = RoundedCornerShape(4.dp)) to apply rounded corners.
*I took a liberty with the dp size as 2px is not easily translatable to dx.

Comment (takahirom) [reply uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt:84]: Certainly the figma design is rounded👀

Comment (maho-ya) [reply uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt:84]: @mightyfrog 
Thanks for the good advice!

@takahirom 
The corners are not rounded.
Do you want to apply what he suggested?

Comment (takahirom) [reply uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt:84]: Since the purpose of the following issue is to show it to the designer, I think that it is better to arrange the appearance, and for that purpose it seems better to round it.
https://github.com/DroidKaigi/conference-app-2021/issues/88
It's okay to do the rounding with this PR, or with another PR. Please choose the one you like.

Comment (maho-ya) [reply uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt:84]: It looks like there are a few things we need to consider for the design.
It would be better to change the roundness after discussing it in #88.

Comment (takahirom) [reply uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt:84]: OK! I will merge this PR! Thank you for thinking!

Comment (maho-ya) [reply uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt:84]: Thank you, too.
